baseURL = "https://adityaparab.com"
title = "Aditya Parab"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 6

[markup]
[markup.highlight]
noClasses = false
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Aditya Parab"
description = "Senior QA Engineer with 12+ years of experience in Software Testing and Test Automation"
keywords = "qa, testing, automation, playwright, selenium, software"
info = ["Senior QA Engineer","Curious Builder"]
avatarURL = "images/profile.jpg"
dateFormat = "January 2, 2006"
colorScheme = "auto"
hideColorSchemeToggle = false

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 1
url = "https://www.linkedin.com/in/adiparab14/"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 2
url = "https://github.com/adiparab14"

[[params.social]]
name = "Email"
icon = "fa-solid fa-envelope fa-2x"
weight = 3
url = "mailto:adiparab14@gmail.com"

[taxonomies]
category = "categories"
tag = "tags"

[languages.en]

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "CityWalker"
weight = 3
url = "citywalker/"

[[languages.en.menu.main]]
name = "Resume"
weight = 4
url = "resume/"
